#  Mark
1. Find => 股票代碼對應產業別
    上市公司基本資料 https://data.gov.tw/dataset/18419
    API =>https://quality.data.gov.tw/dq_download_json.php?nid=18419&md5_url=04541d53fd5cbeb2803e0fe4becc4b97  
2. 解出產業別
    證券代碼編碼原則https://members.sitca.org.tw/OPF/K0000/files/F/01/%E8%AD%89%E5%88%B8%E4%BB%A3%E7%A2%BC%E7%B7%A8%E7%A2%BC%E5%8E%9F%E5%89%87.doc

In [2]:
url = 'https://quality.data.gov.tw/dq_download_json.php?nid=18419&md5_url=04541d53fd5cbeb2803e0fe4becc4b97'
#若有 CSV 可以選用True 做更新 False 會直接讀2021/07/16 下載的資料
updatamappingData=False
 
import json
import requests
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
# Auo proxy Server
#proxies = {"http": "http://auhqwsg.corpnet.auo.com:8080","https": "https://auhqwsg.corpnet.auo.com:8080"}
headers = {
    "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "Accept-Encoding":"gzip, deflate, br",
    "Accept-Language":"zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,und;q=0.5",
    "Cache-Control":"no-cache",
    "Connection":"keep-alive",
    "Host":"data.epa.gov.tw",
    "Pragma":"no-cache",
    "Sec-Fetch-Dest":"document",
    "Sec-Fetch-Mode":"navigate",
    "Sec-Fetch-Site":"none",
    "Sec-Fetch-User":"?1",
    "Upgrade-Insecure-Requests":"1",
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
}
#req = requests.get(url,proxies=proxies, headers = headers,verify=False)
req = requests.get(url, headers = headers,verify=False)
data = json.loads(req.content.decode('utf8'))
df=pd.DataFrame.from_dict(data)
df1=df[['公司代號', '公司名稱', '公司簡稱','產業別']]
 
#【確認資料使用】
#print(df.columns )
#df1.head(5)
#【Distinct 確認資料】 產業別
#mylist = df['產業別']
#{x:1 for x in mylist}.keys()
 
# 【更新資料使用】CSV 轉json
#mappingData=pd.read_csv('Book1.csv',encoding='big5')
#mappingData.to_json()
 
#【來源切換】mapping Data
if updatamappingData:
    mappingData=pd.read_csv('Book1.csv',encoding='big5')   
else:
    aa='{"\\u4e0a\\u5e02\\u516c\\u53f8\\u7522\\u696d\\u985e\\u5225":{"1":"\\u6c34\\u6ce5\\u5de5\\u696d","2":"\\u98df\\u54c1\\u5de5\\u696d","3":"\\u5851\\u81a0\\u5de5\\u696d","4":"\\u7d21\\u7e54\\u7e96\\u7dad","5":"\\u96fb\\u6a5f\\u6a5f\\u68b0","6":"\\u96fb\\u5668\\u96fb\\u7e9c","7":"\\u5316\\u5b78\\u5de5\\u696d","8":"\\u751f\\u6280\\u91ab\\u7642\\u696d","9":"\\u73bb\\u7483\\u9676\\u74f7","10":"\\u9020\\u7d19\\u5de5\\u696d","11":"\\u92fc\\u9435\\u5de5\\u696d","12":"\\u6a61\\u81a0\\u5de5\\u696d","13":"\\u6c7d\\u8eca\\u5de5\\u696d","14":"\\u534a\\u5c0e\\u9ad4\\u696d","15":"\\u96fb\\u8166\\u53ca\\u9031\\u908a\\u8a2d\\u5099\\u696d","16":"\\u5149\\u96fb\\u696d","17":"\\u901a\\u4fe1\\u7db2\\u8def\\u696d","18":"\\u96fb\\u5b50\\u96f6\\u7d44\\u4ef6\\u696d","19":"\\u96fb\\u5b50\\u901a\\u8def\\u696d","20":"\\u8cc7\\u8a0a\\u670d\\u52d9\\u696d","21":"\\u5176\\u4ed6\\u96fb\\u5b50\\u696d","22":"\\u5efa\\u6750\\u71df\\u9020","23":"\\u822a\\u904b\\u696d","24":"\\u89c0\\u5149\\u4e8b\\u696d","25":"\\u91d1\\u878d\\u4fdd\\u96aa","26":"\\u8cbf\\u6613\\u767e\\u8ca8","27":"\\u6cb9\\u96fb\\u71c3\\u6c23\\u696d","28":"\\u7d9c\\u5408","29":"\\u5176\\u4ed6","30":"--","31":"--","32":"--","33":"--"},"\\u4e0a\\u6ac3\\u516c\\u53f8\\u7522\\u696d\\u985e\\u5225":{"1":"--","2":"\\u98df\\u54c1\\u5de5\\u696d","3":"\\u5851\\u81a0\\u5de5\\u696d","4":"\\u7d21\\u7e54\\u7e96\\u7dad","5":"\\u96fb\\u6a5f\\u6a5f\\u68b0","6":"\\u96fb\\u5668\\u96fb\\u7e9c","7":"\\u5316\\u5b78\\u5de5\\u696d","8":"\\u751f\\u6280\\u91ab\\u7642\\u696d","9":"\\u73bb\\u7483\\u9676\\u74f7","10":"--","11":"\\u92fc\\u9435\\u5de5\\u696d","12":"\\u6a61\\u81a0\\u5de5\\u696d","13":"--","14":"\\u534a\\u5c0e\\u9ad4\\u696d","15":"\\u96fb\\u8166\\u53ca\\u9031\\u908a\\u8a2d\\u5099\\u696d","16":"\\u5149\\u96fb\\u696d","17":"\\u901a\\u4fe1\\u7db2\\u8def\\u696d","18":"\\u96fb\\u5b50\\u96f6\\u7d44\\u4ef6\\u696d","19":"\\u96fb\\u5b50\\u901a\\u8def\\u696d","20":"\\u8cc7\\u8a0a\\u670d\\u52d9\\u696d","21":"\\u5176\\u4ed6\\u96fb\\u5b50\\u696d","22":"\\u5efa\\u6750\\u71df\\u9020","23":"\\u822a\\u904b\\u696d","24":"\\u89c0\\u5149\\u4e8b\\u696d","25":"\\u91d1\\u878d\\u696d","26":"\\u8cbf\\u6613\\u767e\\u8ca8","27":"\\u6cb9\\u96fb\\u71c3\\u6c23\\u696d","28":"--","29":"\\u5176\\u4ed6","30":"\\u6587\\u5316\\u5275\\u610f\\u696d","31":"\\u8fb2\\u696d\\u79d1\\u6280\\u696d","32":"\\u96fb\\u5b50\\u5546\\u52d9","33":"\\u7ba1\\u7406\\u80a1\\u7968"},"\\u65b0\\u7de8\\u78bc":{"1":"01","2":"02","3":"03","4":"04","5":"05","6":"06","7":"21","8":"22","9":"08","10":"09","11":"10","12":"11","13":"12","14":"24","15":"25","16":"26","17":"27","18":"28","19":"29","20":"30","21":"31","22":"14","23":"15","24":"16","25":"17","26":"18","27":"23","28":"19","29":"20","30":"32","31":"33","32":"34","33":"80"}}'
    dd= json.loads(aa)
    mappingData=pd.DataFrame.from_dict(dd)   
 
#格式處理
mappingData=mappingData.dropna()
mappingData['新編碼']=mappingData['新編碼'].apply(lambda x:str(x).zfill(2))
#【Data 合併】
df3=pd.merge(df1, mappingData, how='left', left_on='產業別', right_on='新編碼')
df3[df3['公司代號']=="2330"]

     公司代號            公司名稱 公司簡稱 產業別 上市公司產業類別 上櫃公司產業類別 新編碼
276  2330  台灣積體電路製造股份有限公司  台積電  24     半導體業     半導體業  24

In [3]:
df3

     公司代號              公司名稱  公司簡稱 產業別 上市公司產業類別 上櫃公司產業類別 新編碼
0    1101        台灣水泥股份有限公司    台泥  01     水泥工業       --  01
1    1102        亞洲水泥股份有限公司    亞泥  01     水泥工業       --  01
2    1103        嘉新水泥股份有限公司    嘉泥  01     水泥工業       --  01
3    1104        環球水泥股份有限公司    環泥  01     水泥工業       --  01
4    1108        幸福水泥股份有限公司    幸福  01     水泥工業       --  01
..    ...               ...   ...  ..      ...      ...  ..
961  9944        新麗企業股份有限公司    新麗  20       其他       其他  20
962  9945      潤泰創新國際股份有限公司   潤泰新  20       其他       其他  20
963  9946  三發地產股份有限公司(原:金革)  三發地產  14     建材營造     建材營造  14
964  9955      佳龍科技工程股份有限公司    佳龍  20       其他       其他  20
965  9958      世紀鋼鐵結構股份有限公司   世紀鋼  10     鋼鐵工業     鋼鐵工業  10

[966 rows x 7 columns]

In [4]:
df3.to_csv(r'StockBaseData.csv', index = False)