In [26]:
#https://www.codenong.com/20186344/

%run BaseInfo_Company.ipynb
%run BaseInfo_ETFNo.ipynb

In [27]:
import pandas as pd

In [28]:
StockBaseData=pd.read_csv('StockBaseData.csv')
ETFBaseData=pd.read_csv('ETFBaseData.csv')

In [29]:
StockBaseData.head(2)

   公司代號        公司名稱 公司簡稱  產業別 上市公司產業類別 上櫃公司產業類別  新編碼
0  1101  台灣水泥股份有限公司   台泥    1     水泥工業       --  1.0
1  1102  亞洲水泥股份有限公司   亞泥    1     水泥工業       --  1.0

In [30]:
ETFBaseData.head(2)

  股票名稱      持股(千股)     比例      增減  ETF_Id
0  台積電  151,043.00  47.11  -1.83%      50
1  聯發科    9,300.00   4.69  -0.34%      50

## 資料處理

In [31]:
# 兩表Join
df=pd.merge(ETFBaseData, StockBaseData, how='left', left_on='股票名稱', right_on='公司簡稱')
# 處理格式問題
df['ETF_Id']='00'+df['ETF_Id'].astype(str)

#處理上市公司產業類別對應不到的狀況
df['上市公司產業類別']=df['上市公司產業類別'].fillna('未分類')
print(df.columns)

Index(['股票名稱', '持股(千股)', '比例', '增減', 'ETF_Id', '公司代號', '公司名稱', '公司簡稱', '產業別',
       '上市公司產業類別', '上櫃公司產業類別', '新編碼'],
      dtype='object')

In [32]:
df[df['ETF_Id']=='00891']

,股票名稱,持股(千股),比例,增減,ETF_Id,公司代號,公司名稱,公司簡稱,產業別,上市公司產業類別,上櫃公司產業類別,新編碼
1424,聯發科,"1,912.00",19.13,-0.54%,00891,2454.0,聯發科技股份有限公司,聯發科,24.0,半導體業,半導體業,24.0
1425,台積電,"3,057.00",18.92,+0.05%,00891,2330.0,台灣積體電路製造股份有限公司,台積電,24.0,半導體業,半導體業,24.0
1426,聯電,"19,642.00",10.85,+0.09%,00891,2303.0,聯華電子股份有限公司,聯電,24.0,半導體業,半導體業,24.0
1427,日月光投控,"5,416.00",6.31,+0.07%,00891,3711.0,日月光投資控股股份有限公司,日月光投控,24.0,半導體業,半導體業,24.0
1428,矽力-KY,138.00,5.44,+0.20%,00891,6415.0,矽力杰股份有限公司,矽力-KY,24.0,半導體業,半導體業,24.0
1429,聯詠,"1,013.00",5.26,-0.34%,00891,3034.0,聯詠科技股份有限公司,聯詠,24.0,半導體業,半導體業,24.0
1430,瑞昱,790.00,4.15,+0.08%,00891,2379.0,瑞昱半導體股份有限公司,瑞昱,24.0,半導體業,半導體業,24.0
1431,環球晶,365.00,3.49,+0.38%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1432,穩懋,569.00,2.22,+0.34%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1433,世界,"1,564.00",1.92,+0.05%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1434,譜瑞-KY,131.00,1.89,-0.14%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1435,華邦電,"4,662.00",1.69,+0.04%,00891,2344.0,華邦電子股份有限公司,華邦電,24.0,半導體業,半導體業,24.0
1436,中美晶,827.00,1.66,+0.22%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1437,力旺,118.00,1.64,+0.49%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1438,南亞科,"1,942.00",1.61,-0.04%,00891,2408.0,南亞科技股份有限公司,南亞科,24.0,半導體業,半導體業,24.0
1439,旺宏,"3,113.00",1.48,+0.12%,00891,2337.0,旺宏電子股份有限公司,旺宏,24.0,半導體業,半導體業,24.0
1440,大聯大,"2,690.00",1.43,-0.01%,00891,3702.0,大聯大投資控股股份有限公司,大聯大,29.0,電子通路業,電子通路業,29.0
1441,力成,"1,171.00",1.31,+0.01%,00891,6239.0,力成科技股份有限公司,力成,24.0,半導體業,半導體業,24.0
1442,義隆,494.00,1.00,-0.08%,00891,2458.0,義隆電子股份有限公司,義隆,24.0,半導體業,半導體業,24.0
1443,信驊,43.00,0.90,-0.06%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1444,京元電子,"1,863.00",0.87,+0.03%,00891,2449.0,京元電子股份有限公司,京元電子,24.0,半導體業,半導體業,24.0
1445,頎邦,"1,081.00",0.81,+0.06%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1446,祥碩,47.00,0.66,-0.06%,00891,5269.0,祥碩科技股份有限公司,祥碩,24.0,半導體業,半導體業,24.0
1447,創意,142.00,0.61,+0.08%,00891,3443.0,創意電子股份有限公司,創意,24.0,半導體業,半導體業,24.0
1448,南茂,"1,091.00",0.54,+0.02%,00891,8150.0,南茂科技股份有限公司,南茂,24.0,半導體業,半導體業,24.0
1449,立積,91.00,0.46,-0.03%,00891,4968.0,立積電子股份有限公司,立積,24.0,半導體業,半導體業,24.0
1450,精材,256.00,0.45,+0.04%,00891,NaN,NaN,NaN,NaN,未分類,NaN,NaN
1451,超豐,464.00,0.38,+0.04%,00891,2441.0,超豐電子股份有限公司,超豐,24.0,半導體業,半導體業,24.0
1452,健策,108.00,0.34,+0.02%,00891,3653.0,健策精密工業股份有限公司,健策,28.0,電子零組件業,電子零組件業,28.0
1453,文曄,465.00,0.26,0.00%,00891,3036.0,文曄科技股份有限公司,文曄,29.0,電子通路業,電子通路業,29.0

In [33]:
# 取得 etf 對應持股佔比
df['data']=df.agg(lambda x: f"{x['股票名稱']} ( {x['比例']}%)", axis=1)
df.sort_values('比例', ascending=False)
t=df[['ETF_Id','data']]
t[t['ETF_Id']=='00891']

     ETF_Id            data
1424  00891   聯發科 ( 19.13%)
1425  00891   台積電 ( 18.92%)
1426  00891    聯電 ( 10.85%)
1427  00891  日月光投控 ( 6.31%)
1428  00891  矽力-KY ( 5.44%)
1429  00891     聯詠 ( 5.26%)
1430  00891     瑞昱 ( 4.15%)
1431  00891    環球晶 ( 3.49%)
1432  00891     穩懋 ( 2.22%)
1433  00891     世界 ( 1.92%)
1434  00891  譜瑞-KY ( 1.89%)
1435  00891    華邦電 ( 1.69%)
1436  00891    中美晶 ( 1.66%)
1437  00891     力旺 ( 1.64%)
1438  00891    南亞科 ( 1.61%)
1439  00891     旺宏 ( 1.48%)
1440  00891    大聯大 ( 1.43%)
1441  00891     力成 ( 1.31%)
1442  00891      義隆 ( 1.0%)
1443  00891      信驊 ( 0.9%)
1444  00891   京元電子 ( 0.87%)
1445  00891     頎邦 ( 0.81%)
1446  00891     祥碩 ( 0.66%)
1447  00891     創意 ( 0.61%)
1448  00891     南茂 ( 0.54%)
1449  00891     立積 ( 0.46%)
1450  00891     精材 ( 0.45%)
1451  00891     超豐 ( 0.38%)
1452  00891     健策 ( 0.34%)
1453  00891     文曄 ( 0.26%)

In [34]:
keydata=df.groupby(['ETF_Id','上市公司產業類別'])['data'].apply(','.join).reset_index()
keydata

    ETF_Id 上市公司產業類別                                               data
0     0050      光電業                           大立光 ( 1.05%),友達 ( 0.66%)
1     0050       其他                         中租-KY ( 0.84%),豐泰 ( 0.36%)
2     0050    其他電子業                                        鴻海 ( 4.41%)
3     0050     半導體業  台積電 ( 47.11%),聯發科 ( 4.69%),聯電 ( 2.04%),日月光投控 (...
4     0050     塑膠工業                台塑 ( 1.65%),南亞 ( 1.55%),台化 ( 0.96%)
..     ...      ...                                                ...
355  00891   電子零組件業                                        健策 ( 0.34%)
356  00892     半導體業  台積電 ( 23.73%),瑞昱 ( 5.91%),聯發科 ( 5.76%),聯電 ( 5....
357  00892      未分類  環球晶 ( 6.73%),穩懋 ( 5.72%),世界 ( 4.89%),譜瑞-KY ( 4...
358  00892    通信網路業                                        全新 ( 0.98%)
359  00892    電子通路業                                         崇越 ( 0.9%)

[360 rows x 3 columns]

In [35]:
# 取得產業比例排名 by ETF_Id 上市公司產業類別

# 挑選要用的欄位
colList=['ETF_Id','股票名稱', '上市公司產業類別','持股(千股)','比例']
df_=df[colList]
# groupby
g=df_.groupby(['ETF_Id','上市公司產業類別']).sum().reset_index()
# 排序 取前三
#g.sort_values('比例', ascending=False).groupby(['ETF_Id']).head(3).sort_values(['ETF_Id', '比例'], ascending=[True, False])
# 排序(這個對未來比較有彈性)
g['row_numbers'] =g.groupby('ETF_Id')['比例'].rank(ascending=False,method='dense')
g[g['ETF_Id']=='00891']

    ETF_Id 上市公司產業類別     比例  row_numbers
352  00891     半導體業  80.67          1.0
353  00891      未分類  14.98          2.0
354  00891    電子通路業   1.69          3.0
355  00891   電子零組件業   0.34          4.0

In [36]:
#轉成橫的方便看
df1=g[g['row_numbers']==1].merge(keydata,on=['ETF_Id','上市公司產業類別'])
df2=g[g['row_numbers']==2].merge(keydata,on=['ETF_Id','上市公司產業類別'])
df3=g[g['row_numbers']==3].merge(keydata,on=['ETF_Id','上市公司產業類別'])
df_result=df1.merge(df2,on='ETF_Id',suffixes=["","_2"]).merge(df3,on='ETF_Id',suffixes=["","_3"])
df_result = df_result.drop(df_result.filter(regex='row_numbers').columns, axis=1)
df_result

,ETF_Id,上市公司產業類別,比例,data,上市公司產業類別_2,比例_2,data_2,上市公司產業類別_3,比例_3,data_3
0,0050,半導體業,57.81,"台積電 ( 47.11%),聯發科 ( 4.69%),聯電 ( 2.04%),日月光投控 (...",金融保險,11.24,"富邦金 ( 1.79%),國泰金 ( 1.47%),中信金 ( 1.36%),兆豐金 ( 1...",其他電子業,4.41,鴻海 ( 4.41%)
1,0051,電子零組件業,13.08,"欣興 ( 2.61%),華新科 ( 1.75%),健鼎 ( 1.07%),臻鼎-KY ( 1...",電腦及週邊設備業,12.22,"光寶科 ( 1.93%),微星 ( 1.71%),仁寶 ( 1.45%),緯創 ( 1.37...",金融保險,10.75,"開發金 ( 2.9%),永豐金 ( 2.29%),新光金 ( 1.79%),中壽 ( 0.8..."
2,0052,半導體業,75.34,"台積電 ( 59.26%),聯發科 ( 5.95%),聯電 ( 2.59%),日月光投控 (...",電子零組件業,7.40,"台達電 ( 2.74%),國巨 ( 1.06%),欣興 ( 0.69%),華新科 ( 0.4...",其他電子業,6.73,"鴻海 ( 5.59%),可成 ( 0.56%),鴻準 ( 0.3%),旭隼 ( 0.28%)"
3,0053,半導體業,59.31,"台積電 ( 43.35%),聯發科 ( 4.03%),聯電 ( 1.93%),日月光投控 (...",電子零組件業,8.60,"台達電 ( 2.22%),國巨 ( 0.78%),南電 ( 0.71%),欣興 ( 0.52...",電腦及週邊設備業,6.89,"廣達 ( 0.97%),華碩 ( 0.8%),研華 ( 0.74%),緯穎 ( 0.54%)..."
4,0054,其他電子業,20.09,"鴻海 ( 14.65%),可成 ( 1.78%),旭隼 ( 1.42%),致茂 ( 1.01...",電子零組件業,17.56,"台達電 ( 7.63%),國巨 ( 2.8%),華新科 ( 1.03%),台光電 ( 0.8...",塑膠工業,10.62,"南亞 ( 6.13%),台化 ( 4.49%)"
5,0056,電腦及週邊設備業,27.84,"緯創 ( 3.88%),仁寶 ( 3.29%),華碩 ( 3.27%),廣達 ( 3.03%...",光電業,11.58,"友達 ( 4.74%),群創 ( 3.82%),瑞儀 ( 3.02%)",航運業,8.91,長榮 ( 8.91%)
6,0057,半導體業,53.42,"台積電 ( 42.95%),聯發科 ( 4.25%),聯電 ( 1.83%),日月光投控 (...",金融保險,10.98,"富邦金 ( 1.44%),國泰金 ( 1.25%),中信金 ( 1.23%),兆豐金 ( 1...",其他電子業,4.61,"鴻海 ( 4.08%),可成 ( 0.35%),鴻準 ( 0.18%)"
7,006203,半導體業,53.92,"台積電 ( 43.26%),聯發科 ( 4.27%),聯電 ( 1.85%),日月光投控 (...",金融保險,11.05,"富邦金 ( 1.45%),國泰金 ( 1.26%),中信金 ( 1.24%),兆豐金 ( 1...",其他電子業,4.68,"鴻海 ( 4.12%),可成 ( 0.38%),鴻準 ( 0.18%)"
8,006204,半導體業,32.23,"台積電 ( 24.03%),聯發科 ( 2.0%),聯電 ( 1.12%),日月光投控 ( ...",航運業,9.01,"陽明 ( 4.06%),長榮 ( 2.65%),萬海 ( 1.17%),裕民 ( 0.42%...",金融保險,8.96,"國泰金 ( 1.04%),富邦金 ( 1.01%),元大金 ( 0.62%),兆豐金 ( 0..."
9,006208,半導體業,58.00,"台積電 ( 47.28%),聯發科 ( 4.7%),聯電 ( 2.05%),日月光投控 ( ...",金融保險,11.26,"富邦金 ( 1.8%),國泰金 ( 1.47%),中信金 ( 1.36%),兆豐金 ( 1....",其他電子業,4.42,鴻海 ( 4.42%)
10,00690,半導體業,44.90,"台積電 ( 28.29%),聯發科 ( 10.18%),矽力-KY ( 2.12%),聯詠 ...",金融保險,13.77,"富邦金 ( 3.85%),國泰金 ( 3.27%),中信金 ( 3.07%),兆豐金 ( 2...",塑膠工業,9.67,"台塑 ( 3.85%),南亞 ( 3.22%),台化 ( 2.6%)"
11,00692,半導體業,52.10,"台積電 ( 42.64%),聯發科 ( 4.23%),聯電 ( 1.82%),日月光投控 (...",金融保險,14.17,"富邦金 ( 2.09%),國泰金 ( 1.96%),兆豐金 ( 1.23%),中信金 ( 1...",塑膠工業,5.06,"南亞 ( 1.82%),台塑 ( 1.81%),台化 ( 1.37%),亞聚 ( 0.06%)"
12,00701,金融保險,62.26,"富邦金 ( 9.1%),國泰金 ( 7.61%),中信金 ( 7.15%),兆豐金 ( 5....",通信網路業,12.90,"中華電 ( 9.48%),台灣大 ( 3.42%)",水泥工業,6.07,"台泥 ( 4.1%),亞泥 ( 1.97%)"
13,00713,金融保險,22.44,"第一金 ( 7.16%),國泰金 ( 4.24%),華票 ( 1.99%),京城銀 ( 1....",電腦及週邊設備業,14.33,"光寶科 ( 4.42%),仁寶 ( 2.79%),神基 ( 1.38%),英業達 ( 1.3...",食品工業,13.92,"統一 ( 8.91%),大統益 ( 2.01%),卜蜂 ( 1.98%),大成 ( 1.02%)"
14,00728,半導體業,59.56,"台積電 ( 29.04%),聯發科 ( 14.15%),矽力-KY ( 5.88%),聯詠 ...",塑膠工業,13.98,"台塑 ( 5.6%),南亞 ( 4.64%),台化 ( 3.74%)",光電業,5.14,"大立光 ( 4.05%),玉晶光 ( 1.09%)"
15,00730,水泥工業,19.50,"亞泥 ( 9.79%),台泥 ( 9.71%)",電腦及週邊設備業,14.46,"光寶科 ( 7.87%),緯創 ( 5.45%),神基 ( 1.14%)",未分類,12.72,"大江 ( 4.16%),東洋 ( 3.07%),精華 ( 2.15%),聖暉 ( 1.68%..."
16,00731,金融保險,42.87,"富邦金 ( 8.17%),國泰金 ( 6.68%),中信金 ( 6.17%),兆豐金 ( 5...",電腦及週邊設備業,11.93,"華碩 ( 3.98%),廣達 ( 3.52%),光寶科 ( 1.85%),仁寶 ( 1.38...",塑膠工業,11.89,"台塑 ( 7.52%),台化 ( 4.37%)"
17,00733,航運業,23.12,"陽明 ( 15.94%),慧洋-KY ( 4.33%),台驊投控 ( 2.03%),台航 (...",半導體業,19.32,"天鈺 ( 3.0%),愛普 ( 2.89%),敦泰 ( 2.79%),景碩 ( 2.72%)...",其他,17.97,"巨大 ( 6.84%),美利達 ( 4.89%),潤泰新 ( 4.39%),裕融 ( 1.85%)"
18,00742,通信網路業,29.94,"中華電 ( 17.8%),台灣大 ( 6.47%),遠傳 ( 5.67%)",水泥工業,17.17,"台泥 ( 10.86%),亞泥 ( 6.31%)",汽車工業,10.26,"和泰車 ( 5.11%),裕日車 ( 3.06%),中華 ( 2.09%)"
19,00850,半導體業,40.79,"台積電 ( 28.6%),聯發科 ( 6.03%),聯電 ( 2.62%),日月光投控 ( ...",金融保險,16.30,"富邦金 ( 2.3%),國泰金 ( 1.89%),中信金 ( 1.74%),兆豐金 ( 1....",其他電子業,6.22,"鴻海 ( 5.66%),可成 ( 0.56%)"
20,00878,電腦及週邊設備業,25.39,"緯創 ( 4.16%),英業達 ( 4.03%),仁寶 ( 3.96%),光寶科 ( 3.7...",金融保險,22.68,"兆豐金 ( 3.64%),開發金 ( 3.6%),永豐金 ( 3.56%),中信金 ( 3....",通信網路業,9.22,"遠傳 ( 3.34%),台灣大 ( 3.27%),中華電 ( 2.61%)"
21,00881,半導體業,57.13,"台積電 ( 29.67%),聯發科 ( 12.59%),聯電 ( 5.37%),矽力-KY ...",其他電子業,13.08,"鴻海 ( 12.23%),致茂 ( 0.85%)",電腦及週邊設備業,7.68,"廣達 ( 2.54%),和碩 ( 1.64%),仁寶 ( 1.04%),緯創 ( 0.97%..."
22,00891,半導體業,80.67,"聯發科 ( 19.13%),台積電 ( 18.92%),聯電 ( 10.85%),日月光投控...",未分類,14.98,"環球晶 ( 3.49%),穩懋 ( 2.22%),世界 ( 1.92%),譜瑞-KY ( 1...",電子通路業,1.69,"大聯大 ( 1.43%),文曄 ( 0.26%)"
23,00892,半導體業,55.90,"台積電 ( 23.73%),瑞昱 ( 5.91%),聯發科 ( 5.76%),聯電 ( 5....",未分類,40.72,"環球晶 ( 6.73%),穩懋 ( 5.72%),世界 ( 4.89%),譜瑞-KY ( 4...",通信網路業,0.98,全新 ( 0.98%)